// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2vHn5mpLsCGL2mHNlfbdAAv2I_rqDnw',
    appId: '1:152248316877:web:099d61222169c655efca84',
    messagingSenderId: '152248316877',
    projectId: 'cmandi-a2dc0',
    authDomain: 'cmandi-a2dc0.firebaseapp.com',
    storageBucket: 'cmandi-a2dc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR3dOVa2run7tYUXnsbKsVxKEUx959Dmg',
    appId: '1:152248316877:android:51002872d1c907f4efca84',
    messagingSenderId: '152248316877',
    projectId: 'cmandi-a2dc0',
    storageBucket: 'cmandi-a2dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDunn5zo_jX9okosL0Ht_9Au1cehhnUgU',
    appId: '1:152248316877:ios:a1c869d74f1f88bcefca84',
    messagingSenderId: '152248316877',
    projectId: 'cmandi-a2dc0',
    storageBucket: 'cmandi-a2dc0.firebasestorage.app',
    iosBundleId: 'com.example.cmandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDunn5zo_jX9okosL0Ht_9Au1cehhnUgU',
    appId: '1:152248316877:ios:a1c869d74f1f88bcefca84',
    messagingSenderId: '152248316877',
    projectId: 'cmandi-a2dc0',
    storageBucket: 'cmandi-a2dc0.firebasestorage.app',
    iosBundleId: 'com.example.cmandi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe2vHn5mpLsCGL2mHNlfbdAAv2I_rqDnw',
    appId: '1:152248316877:web:187e9e114599b00fefca84',
    messagingSenderId: '152248316877',
    projectId: 'cmandi-a2dc0',
    authDomain: 'cmandi-a2dc0.firebaseapp.com',
    storageBucket: 'cmandi-a2dc0.firebasestorage.app',
  );
}
